enableTelemetry: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: "https://yarn.build/latest"
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.1.0/index.js"

yarnPath: .yarn/releases/yarn-3.8.0.cjs
